### ISSUE TITLE
Add spinner to Giphy plugin when using shuffle action

### ISSUE THREAD

**Issue by DHaussermann** [levb/mattermost-giphy-plugin#3]
Currently when using the Giphy plugin there is no visual feedback that you have clicked the shuffle button. In the case where shuffle lands on the same image, this can make the button appear unresponsive. 

We need to add a spinner to indicate that the shuffle button was clicked and the image is cycling.

**Comment by levb** [comment]
@DHaussermann since this plugin is 100% server-side, it lacks the ability to do it without creating an entire new layer of webapp component(s). I suggest that you file an improvement against mattermost-webapp to display spinners when PostActions are invoked.
